GET http://localhost:3003/users

###

POST http://localhost:3003/users
Content-Type: application/json; charset=utf-8

{
  "name": "Francisco Kleuvys",
  "email": "franciso@kleuvys.com",
  "password": "1",
  "photo": "https://avatars.githubusercontent.com/u/43152383?v=4",
  "phone": "(11) 99999-0000",
  "role": "Dev"
}

###

POST http://localhost:3003/skills/24
Content-Type: application/json; charset=utf-8

{
  "skills": ["html", "css", "javascript"]
}


###
POST http://localhost:3003/posts
Content-Type: application/json; charset=utf-8

{
  "userID": "24",
  "title": "Ofsadfasdfsdfie",
  "body": "Opa!!!",
  "skills": ["html", "css", "javascript"]
}

###
GET http://localhost:3003/posts/04ed1e1b-f130-4401-aed8-aaa2bd673dc1

###
POST http://localhost:3003/posts/851275da-11b7-4776-97af-2e284695d3ea/comment
Content-Type: application/json; charset=utf-8

{
    "userID": "14",
  "body": "Opa231!!!"
}

###
GET http://localhost:3003/posts/

###
DELETE http://localhost:3003/skills
Content-Type: application/json; charset=utf-8

{
  "user_id": "4"
}

###
POST http://localhost:3003/login
Content-Type: application/json; charset=utf-8

{
  "email": "claytn@charles.com",
  "password": "carloscleiton1"
}

###

POST http://localhost:3003/users
Content-Type: application/json; charset=utf-8

{
        "name": "Cleiton Carlos",
        "email": "cleitito@fcamara.com",
        "password": "#95e24d",
        "photo": "https://ibb.co/tBhcb0s",
        "phone": "(45) 49058-8168",
        "role": "CEo do seu coração"
}

###
POST http://localhost:3003/skills/204
Content-Type: application/json; charset=utf-8

{
    "skills": ["carinho", "compaixão", "sorriso", "barata"]
}

###
    {
        "name": "Cleiton Carlos",
        "email": "cleitito@fcamara.com",
        "password": "#95e24d",
        "photo": "https://ibb.co/tBhcb0s",
        "phone": "(45) 49058-8168",
        "role": "CEo do seu coração",
        "skills": ["carinho", "compaixão", "sorriso", "barata"]
    }
]